"""Generate airports.js: IATA code -> city, IANA time zone, latitude, longitude.

Airports with scheduled service come from OurAirports (public domain). Time zones come from
mwgg/Airports (MIT); airports missing there use the most common time zone in their region.

Usage: python tools/build_airports.py
"""
import csv
import io
import json
import re
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path

OURAIRPORTS_URL = 'https://davidmegginson.github.io/ourairports-data/airports.csv'
MWGG_URL = 'https://raw.githubusercontent.com/mwgg/Airports/master/airports.json'
OUTPUT = Path(__file__).resolve().parent.parent / 'airports.js'


def fetch(url):
    with urllib.request.urlopen(url) as response:
        return response.read().decode('utf-8')


def main():
    mwgg = json.loads(fetch(MWGG_URL))
    tz_by_iata = {a['iata']: a['tz'] for a in mwgg.values() if a.get('iata') and a.get('tz')}
    tz_by_icao = {icao: a['tz'] for icao, a in mwgg.items() if a.get('tz')}

    rows = []
    region_tz = defaultdict(Counter)
    for r in csv.DictReader(io.StringIO(fetch(OURAIRPORTS_URL))):
        code = r['iata_code'].strip()
        if r['scheduled_service'] != 'yes' or r['type'] == 'closed' or not re.fullmatch('[A-Z]{3}', code):
            continue
        tz = tz_by_iata.get(code) or tz_by_icao.get(r['icao_code']) or tz_by_icao.get(r['ident'])
        if tz:
            region_tz[r['iso_region']][tz] += 1
        city = re.sub(r'\s*\(.*?\)', '', r['municipality'] or r['name']).strip().replace('`', '').replace('|', '')
        rows.append((code, city, tz, r['iso_region'], float(r['latitude_deg']), float(r['longitude_deg'])))

    airports = {}
    for code, city, tz, region, lat, lon in rows:
        if not tz and region_tz[region]:
            tz = region_tz[region].most_common(1)[0][0]
        if tz and code not in airports:
            airports[code] = (city, tz, lat, lon)

    zones = sorted({a[1] for a in airports.values()})
    zone_index = {zone: i for i, zone in enumerate(zones)}
    lines = [
        '// Airports with scheduled service: IATA code -> [city, IANA time zone, latitude, longitude].',
        '// Generated by tools/build_airports.py from OurAirports (public domain) and mwgg/Airports (MIT) time zones.',
        'const AIRPORT_TIME_ZONES = ' + json.dumps(zones, separators=(',', ':')) + ';',
        'const AIRPORTS = Object.fromEntries(`',
    ]
    lines += [f'{code}|{city}|{zone_index[tz]}|{lat:.2f}|{lon:.2f}'
              for code, (city, tz, lat, lon) in sorted(airports.items())]
    lines += [
        r"`.trim().split('\n').map(line => {",
        "    const [code, city, tz, lat, lon] = line.split('|');",
        '    return [code, [city, AIRPORT_TIME_ZONES[tz], Number(lat), Number(lon)]];',
        '}));',
        '',
    ]
    OUTPUT.write_text('\n'.join(lines), encoding='utf-8', newline='\n')
    print(f'Wrote {len(airports)} airports in {len(zones)} time zones to {OUTPUT.name}')


if __name__ == '__main__':
    main()
